### PR TITLE
47 prepare workflow test to measure registry readwrite performance

### PR DESCRIPTION
**Pull request by Rumo99**
Includes the following changes:

- Adds basic performance tests
- Implements VolatilePersistentRegistry for peformance tests
- Changes tests to work with VolatilePersistentRegistry 
    - Fixes issue #53 
- Simplifies applyUpdate Method in AbstractPersistentRegistry

### CODE REVIEW

**Review by KKegel — APPROVED** [review]

**Comment by KKegel** [comment]
Should I merge this directly?

**Comment by KKegel** [comment]
@Rumo99 Why does this lower the test coverage to such an extend? can I merge it nonetheless?

**Comment by Rumo99** [comment]
@KKegel Can't really say. Codecov doesn't really offer any insights. Beyond the failing tests due to futures, I don't see a reason this shouldn't be merged, though.

**Comment by KKegel** [comment]
@Rumo99 @Bizarious I just fixed this

**Pull request merged**
